
name: 'deel'
version: '1.0.0'
config-version: 2

profile: 'deel'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  deel:
    staging:
      +materialized: view
      +schema: staging
      globepay:
        base:
          +materialized: ephemeral
          +schema: internal
    intermediate:
      +materialized: ephemeral
      +schema: internal
    marts:
      +materialized: table
      finance:
        +schema: marts_finance